In [1]:
!pip install numpy

In [5]:
import numpy
a = numpy.array([1,2,3])
print(a)

[1 2 3]


In [6]:
a = numpy.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
arr = numpy.array([[1,2,3,4],[4,5,6,7],[9,10,11,12]])
print(arr.ndim)

2


In [9]:
print("Printing array: ")
print(arr)
print("Iterating over the array: ")
for x in numpy.nditer(arr):
    print(x,end='')

Printing array: 
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 12]]
Iterating over the array: 
123445679101112

In [10]:
# INTRO TO NUMPY

In [11]:
my_list=[1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


In [12]:
import numpy as np

In [13]:
array = np.array(my_list, dtype=int)
print(array)

[1 2 3 4 5 6]


In [14]:
print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [15]:
array2=array.reshape(3,2)
print(array2)
array2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [16]:
array3 = array.reshape(3,-1)
print(array3)


print(array3.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [17]:
# Initializing numpy arrays from nested Python lists

my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [9,7,6,8,9]

mul_arr = np.array([my_list2, my_list3, my_list4])
print(mul_arr)

print(mul_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)


In [18]:
mul_arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [19]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [20]:
# Reshaping the ndarray
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
# Reshape function to resize an array
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
r=range(24)

In [23]:
print(r)

range(0, 24)


In [25]:
# An array of evenly spaced numbers
a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [26]:
# Reshaping the array 'a'
b=a.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [27]:
# dtype of array is int8 (1 byte)
x = np.array([1,2,3,4,5], dtype=np.int8)
print(x.itemsize)

1


In [28]:
# dtype of array is now float32 (4 bytes)
x=np.array([1,2,3,4,5], dtype=np.float32)
print(x.itemsize)

4


In [29]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [30]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [31]:
# Lab 6 Assignment

In [32]:
# 1. Reverse the columns of 2d-array

original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

reversed_array = np.fliplr(original_array)

print("Original Array:")
print(original_array)
print("\nReversed Array:")
print(reversed_array)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reversed Array:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [36]:
# 2. Create a 2d-array containing random floats between 5 and 10

rows = 3
cols = 4

array = np.random.uniform(low=5, high=10, size=(rows, cols))

print(array)


[[6.2154313  6.54245363 6.63857081 6.35603574]
 [7.91949072 7.22574862 5.13593776 6.59149834]
 [5.75290863 9.21687325 5.49596833 6.13088177]]


In [38]:
# 3. Find the percentile scores of a numpy array

data = np.array([25, 28, 34, 12, 56, 23, 45, 19, 31, 42])

percentiles = np.percentile(data, [25, 50, 75])

print("Percentiles:")
print(f"25th percentile: {percentiles[0]}")
print(f"50th percentile (median): {percentiles[1]}")
print(f"75th percentile: {percentiles[2]}")


Percentiles:
25th percentile: 23.5
50th percentile (median): 29.5
75th percentile: 40.0


In [40]:
# 4. Find the position of a missing value in a numpy array

array = np.array([1, 2, np.nan, 4, 5])

missing_value_position = np.where(np.isnan(array))[0]

if missing_value_position.size > 0:
  print("Position of the first missing value:", missing_value_position[0])
else:
  print("No missing values found in the array.")


Position of the first missing value: 2


In [46]:
# 5. Sort a 2D array by column

array = np.array([[8,8,8], [5, 2, 6], [7, 8, 9]])
print("Before Sorting: ")
print (array)

print("After Sorting: ")

sorted_array = np.sort(array, axis=0)  
print(sorted_array)

Before Sorting: 
[[8 8 8]
 [5 2 6]
 [7 8 9]]
After Sorting: 
[[5 2 6]
 [7 8 8]
 [8 8 9]]


In [52]:
# 6. Find the most frequent value in a numpy array

array = np.array([2, 3, 2, 1, 2, 3, 5, 2, 3, 2])
counts = np.bincount(array)
most_frequent_value = array[np.argmax(counts)]

print("Most frequent value:", most_frequent_value)

Most frequent value: 2
